//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartyManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public long SerialNo { get; set; }
        public string OrderItem { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public string RoomId { get; set; }
        public string UserName { get; set; }
        public string Sponsor { get; set; }
        public Nullable<System.DateTime> CanceledTime { get; set; }
        public Nullable<bool> isServed { get; set; }
        public Nullable<bool> isCanceled { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string Remark { get; set; }
    }
}
